# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    strategy:
     parallel: 1
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
#        tags: |
#          $(tag)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          sudo apt-get install wget
          wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
          tar xf openshift-client-linux.tar.gz
          mv {oc,kubectl} /usr/local/bin
          oc login https://api.flab-ocp.f-lab.experteam.com.tw:6443 --token=$(OC_TOKEN)
          oc new-build 
          cat $(Build.SourcesDirectory)/app/Dockerfile | oc new-build --name js-app --dockerfile='-' -n azure-devops-pipeline