# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    strategy:
     parallel: 1
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
#        tags: |
#          $(tag)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          wget -q https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
          tar xf openshift-client-linux.tar.gz
          sudo mv {oc,kubectl} /usr/local/bin
          oc login https://api.flab-ocp.f-lab.experteam.com.tw:6443 --token=$(OC_TOKEN) --insecure-skip-tls-verify=true

          
          if ! oc get deployment/js-app -n azure-devops-pipeline -o json; then
            oc new-app --name js-app -n azure-devops-pipeline https://github.com/elleryq/pipelines-javascript-docker --context-dir=/app --strategy=docker
          else
            oc start-build --name js-app
          fi
